# Generated by Django 4.1.7 on 2023-03-30 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0005_remove_comment_approved_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent_comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="approved_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.comment",
                    ),
                ),
            ],
        ),
    ]
