# Generated by Django 4.1.7 on 2023-03-30 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_remove_comment_parent_comment_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
