# Generated by Django 4.1.7 on 2023-03-30 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_reply"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
