# Generated by Django 4.1.7 on 2023-03-30 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_delete_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_date",
            new_name="comment_date",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="commented",
        ),
    ]
