# Generated by Django 4.1.7 on 2023-03-30 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_rename_commented_comment_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="commented",
        ),
    ]
