# Generated by Django 4.1.7 on 2023-03-30 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_remove_comment_approved_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="commented",
        ),
    ]
