# Generated by Django 4.1.7 on 2023-03-30 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_rename_author_comment_commented"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="commented",
            new_name="author",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blog.comment",
            ),
        ),
    ]
