# Generated by Django 4.1.7 on 2023-03-30 03:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_rename_commented_comment_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent_comment",
        ),
    ]
