# Generated by Django 4.1.7 on 2023-03-30 04:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0022_rename_comment_comment_comment_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_text",
            new_name="comment",
        ),
    ]
