# Generated by Django 4.1.7 on 2023-03-30 04:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0023_rename_comment_user_comment_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="comment_text",
        ),
    ]
