# Generated by Django 4.1.7 on 2023-03-30 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0024_rename_comment_comment_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_commented",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
