# Generated by Django 4.1.7 on 2023-03-30 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0025_alter_comment_date_commented_alter_post_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_commented",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
